config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/contact'
  get 'home/about'
  get 'home/privilege'
  get 'home/role_permission_privilage'
  devise_for :users
  root to: "home#index"
  get 'set_access_permissions' => "home#set_access_permissions"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  
  def initialize(user)
     user ||= User.new # guest user (not logged in)
    #Admin
    if user.admin?
      can :manage, :all
    # employee
    elsif user.employee?
      can :read, :index
      cannot :read, :contact
    #Manager
    elsif user.manager?
      can :read, :about
      can :read, :contact
      cannot :read, :index
    else
      can :read, :all
    end
  end
end

#can :read, :index if user.has_attribute? :admin

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
          enum role: [:admin, :manager, :employee]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!
    
   
	

   protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:role, :name])
	end
    
	rescue_from CanCan::AccessDenied do |exception|
		flash[:error] = "Access denied."
		redirect_to root_url
	end

	
	 



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :check_access_for_actions, only: [:index, :contact, :about]
	
  def index
  end

  def contact
  end

  def about
  end

  def privilage
    if home = {:employee=> Page.where(user_role: :employee,page_name: :home).present?, :manager=>Page.where(user_role: :manager,page_name: :home).present?}
      return true
    elsif home = {:employee=> Page.where(user_role: :employee,page_name: :home).present?, :manager=>Page.where(user_role: :manager,page_name: :home).present?}
      return false
    end
  end

  def role_permission_privilage
    if params[:checked]
      @page = Page.new(:user_role => params[:user_role], :page_name => params[:page_name])
      @page.save
    else
      @page = Page.find (params[:id])
      @page.destroy
    end
  end

  def set_access_permissions
    @page = Page.find(params[:page_id])
    if params[:role] == "employee"
      @page.update(access_to_employee: params[:access_allowed])
    elsif params[:role] == "manager"
      @page.update(access_to_manager: params[:access_allowed])
    end
    respond_to do |format|
      format.js 
    end 

  end

  private 

    def check_access_for_actions
      if params[:action] == "index"
        @page = Page.find_by(page_name: params[:controller])
      else
        @page = Page.find_by(page_name: params[:action])
      end
      if !@page.access_to_employee && current_user.role == "employee"
        @alert = "You are not allowed to access this page because you have an employee role and your administration has not assigned any permissions access this page."
      elsif !@page.access_to_manager && current_user.role == "manager"
        @alert = "You are not allowed to access this page because you have a manager role and your administration has not assigned any permissions access this page."
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	
    def index
		@users = User.all
    end

    def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		@user.save
		redirect_to users_path
	end

 	def edit
 		@user = User.find (params[:id])
 	end

 	def update
 		@user = User.find (params[:id])
 		if @user.update(user_params)
 		   redirect_to users_path
 			
 		else
 			render 'edit'
 		end
 	end

 	def destroy
 		@user = User.find (params[:id])
 		@user.destroy
 		redirect_to users_path
 	end

 	

 	

	private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<% if @alert.present? %>
  <div class="p-5">
    <h4 class="text-danger"><%= @alert %></h4>
  </div>
<% else %>
  <div class="jumbotron text-center">
    <h1>My First Bootstrap Page</h1>
    <p>Resize this responsive page to see the effect!</p> 
  </div>
    
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <h3>Column 1</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
        <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
      </div>
      <div class="col-sm-4">
        <h3>Column 2</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
        <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
      </div>
      <div class="col-sm-4">
        <h3>Column 3</h3>        
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
        <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
      </div>
    </div>
  </div>
<% end %>

app/views/home/contact.html.erb
<% if @alert.present? %>
  <div class="p-5">
    <h4 class="text-danger"><%= @alert %></h4>
  </div>
<% else %>
  
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  <div class="container">
    <h2 class="text-center">Contact Form</h2>
    <div class="row justify-content-center">
      <div class="col-12 col-md-8 col-lg-6 pb-5">
        <form action="mail.php" method="post">
          <div class="card border-primary rounded-0">
            <div class="card-header p-0">
              <div class="bg-info text-white text-center py-2">
                <h3><i class="fa fa-envelope"></i> Contactanos</h3>
                <p class="m-0">Con gusto te ayudaremos</p>
              </div>
            </div>
            <div class="card-body p-3">

              <!--Body-->
              <div class="form-group">
                <div class="input-group mb-2">
                  <div class="input-group-prepend">
                    <div class="input-group-text"><i class="fa fa-user text-info"></i></div>
                  </div>
                  <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre y Apellido" required>
                </div>
              </div>
              <div class="form-group">
                <div class="input-group mb-2">
                  <div class="input-group-prepend">
                    <div class="input-group-text"><i class="fa fa-envelope text-info"></i></div>
                  </div>
                  <input type="email" class="form-control" id="nombre" name="email" placeholder="ejemplo@gmail.com" required>
                </div>
              </div>

              <div class="form-group">
                <div class="input-group mb-2">
                  <div class="input-group-prepend">
                    <div class="input-group-text"><i class="fa fa-comment text-info"></i></div>
                  </div>
                  <textarea class="form-control" placeholder="Envianos tu Mensaje" required></textarea>
                </div>
              </div>

              <div class="text-center">
                <input type="submit" value="Enviar" class="btn btn-info btn-block rounded-0 py-2">
              </div>
            </div>

          </div>
        </form>
      </div>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<% if @alert.present? %>
	<div class="p-5">
	    <h4 class="text-danger"><%= @alert %></h4>
	  </div>
<% else %>
	<div class="jumbotron">
	  <h1 class="display-4">Hello, world!</h1>
	  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
	  <hr class="my-4">
	  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
	  <p class="lead">
	    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
	  </p>
	</div>
<% end %>

app/views/home/privilege.html.erb
<div class="container">
             
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Employee</th>
        <th>Manager</th>
        
      </tr>
    </thead>
    <tbody>

      <% Page.order(:page_name).each do |page| %>
        <tr>
          <td><%= page.page_name.titleize %></td>
          <td>
            <% if page.access_to_employee %>
              <input type="checkbox" class="access_check" data-page-id="<%= page.id %>" data-role-name="employee" checked >
            <% else %>
              <input type="checkbox" class="access_check" data-page-id="<%= page.id %>" data-role-name="employee">
            <% end %>
          </td>
          <td>
            <% if page.access_to_manager %>
              <input type="checkbox" class="access_check" data-page-id="<%= page.id %>" data-role-name="manager" checked >
            <% else %>
              <input type="checkbox" class="access_check" data-page-id="<%= page.id %>" data-role-name="manager">
            <% end %>
          </td>
        </tr>
      <% end %>

      <!-- <tr>
        <td>Home</td>

        <td> <input type="checkbox" class="form-check-input" value="home[:employee]"  data-page_name= "home" data-user_role= "employee" id="materialUnchecked"></td>

        <td> <input type="checkbox" class="form-check-input" value="home[:manager]"
         data-page_name= "home" data-user_role= "manager" id="materialUnchecked"></td>
       
      </tr>
      <tr>
        <td>About</td>
        <td> <input type="checkbox" class="form-check-input" value="about[:employee]"  data-page_name= "about" data-user_role= "employee" id="materialUnchecked"></td>
        <td> <input type="checkbox" class="form-check-input" value="about[:manager]" data-page_name= "about" data-user_role= "manager" id="materialUnchecked"></td>
       
      </tr>
      <tr>
        <td>Contact</td>
        <td> <input type="checkbox" class="form-check-input"  value="contact[:employee]" data-page_name= "contact" data-user_role= "employee" id="materialUnchecked"></td>
        <td> <input type="checkbox" class="form-check-input" value="contact[:manager]"  data-page_name= "contact" data-user_role= "manager" id="materialUnchecked"></td>
       
      </tr> -->
    </tbody>
  </table>
</div>
<script>
  
//   $(".form-check-input").change(function() {
//     var checked = $(this).is(':checked');
//     var page_name = $(this).data('page_name');
//     var user_role = $(this).data('user_role');
//   $.ajax({
//       url: "role_permission_privilage",
//       type: "get",
//       data: {checked: checked, page_name: page_name, user_role: user_role},
//       success: function (data) { 
          
//       }
//   });
// });


  $(document).ready(function(){
    $('.access_check').on('click', function(){
      var accessToEmp = $(this).prop("checked");
      var pageId = $(this).data("page-id");
      var roleName = $(this).data("role-name");
      $.ajax({
        url: '/set_access_permissions', 
        method: 'GET', 
        data: {
          access_allowed: accessToEmp, 
          page_id: pageId, 
          role: roleName
        }
      });
    });
  });

</script>

app/views/home/set_access_permissions.js.erb
window.location.href = '/home/privilege';

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light" >
  <a class="navbar-brand logo-text" href="#">Demo Permission</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
       <%= link_to "Home", home_index_path, class: "nav-link" %>
      </li>
    
    
      <li class="nav-item">

         <%= link_to "Contact", home_contact_path, class: "nav-link" %>
         
      </li>
      <li class="nav-item">
       
         <%= link_to "About", home_about_path, class: "nav-link" %>
      </li>
       <% if current_user.try(:admin?) %>
         <li class="nav-item">
          <%= link_to "Privilege", home_privilege_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>



    <ul class="navbar-nav my-lg-0" >
     <% if user_signed_in? %>
        <li>
          <%= link_to('Logout', destroy_user_session_path, class: "btn btn-secondary", method: :delete) %>        
        </li>

        <% else %>
        <li><%= link_to "Sign up", new_user_registration_path, class: "btn btn-secondary", :style =>"margin-right:20px" %></li>
        <li>
          <%= link_to 'Login', new_user_session_path,class: "btn btn-secondary" %>  
        </li>
      <% end %> 
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoPermissionApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>